version: '2'

services:
  phonebook-mysql:
    container_name: phonebook-mysql
    image: localhost:5000/mysql
    restart: always

  phonebook-app:
    container_name: phonebook-app
    image: localhost:5000/myapp
    depends_on:
      - phonebook-mysql
    ports:
      - "8181:8181"
    restart: always
