version: '3'

services:
  phonebook-mysql:
    image: localhost:5000/mysql
    deploy:
      placement:
        constraints: [node.role == manager]
  phonebook-app:
    image: localhost:5000/myapp
    ports:
      - "8181:8181"
    depends_on:
      - phonebook-mysql
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
