name: Flask Auto-Deploy

on: [push]

jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: rebuild and push new version
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~
            git clone https://github.com/ErfanAY/tdfs-crud.git
            cd tdfs-crud
            sudo docker build -t localhost:5000/mysql --target img1 .
            sudo docker build -t localhost:5000/myapp --target img2 .
            sudo docker push localhost:5000/mysql
            sudo docker push localhost:5000/myapp
